feat: add dry-run support for core deploy (#3558)
**Original PR:
https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/3305**

### Description

* New feature to allow users to dry-run the core deploy script against a
forked network of their choice
* To run: `yarn build && yarn hyperlane deploy core --dry-run` || `yarn
build && yarn hyperlane deploy core -d`
* Externally enables: `hyperlane deploy core --dry-run` || `hyperlane
deploy core -d`

### Drive-by changes

* For all touched paths:
  * Code cleanliness + reuse
  * Method docs
  * Minor changes for increased symmetry

### Related issues

* Fixes https://github.com/hyperlane-xyz/issues/issues/819

### Backward compatibility

* Yes

### Testing

* Note: `hl` == `yarn build && yarn hyperlane`. The below tests are only
a sample and are not inclusive.

#### Manual Testing
  * With `anvil` NOT running in separate instance:
    * `hl deploy core -d`
      * Throws:
```
Error: No active anvil node detected.
        Please run `anvil` in a separate instance.
```
  * With `anvil` running in separate instance:
* `hl deploy core -d --targets alfajores -k
c0052e22df5d1f4ae7c51e254Xx00Xx0eb833453eaed6301xXxxx8a30d92d10a` (any
private key)
* Throws `Error: Invalid address length. Please ensure you are passing
an address and not a private key.`
* `hl deploy core -d --targets bsctestnet -k
0x16F4898F47c085C41d7Cc6b1dc0xX0xXX017dcBb` (any public address; BSC
public RPC endpoint does not support forking)
* Output: `⛔️ [dry-run] The current RPC may not support forking. Please
consider using a different RPC provider.`
* `hl deploy core -d --targets alfajores -k
0x16F4898F47c085C41d7Cc6b1dc0xX0xXX017dcBb` (any public address)
     * Output:
```
Verifying anvil node is running...
Successfully verified anvil node is running ✅
No chain config file provided
Forking alfajores for dry-run...
Successfully forked alfajores for dry-run ✅
Impersonating account (0x16F4898F47c085C41d7Cc6b1dc72B91EA617dcBb)...
Successfully impersonated account (0x16F4898F47c085C41d7Cc6b1dc72B91EA617dcBb) ✅
...
Core contracts deployed
Writing agent configs
Agent configs written
Deployment is complete!
Contract address artifacts are in artifacts/dry-run_core-deployment-2024-02-23-15-51-45.json
Agent configs are in artifacts/dry-run_agent-config-2024-02-23-15-51-45.json
Resetting forked network...
Successfully reset forked network ✅
```

#### CI Testing
* Successful CI-backed integration/regression testing via `ci-test.sh`
(includes script refactor)