fix: GCS folder support (#4652)
### Description

This PR fixes the problem of this issue:
[https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/4449](url)
The change was only in the gcs_storage.rs file. Slightly tweaked methods
so that you can write files to a specified folder in the terminal.

When trying to run a validator specifying checkpointSyncer settings for
GCS:
`--checkpointSyncer.type gcs --checkpointSyncer.bucket
an-s3-signatures-repository --checkpointSyncer.folder atletaolympia`

```
Building provider without signer
thread 'main' panicked at 'Failed to report agent metadata: error validating bucket name an-s3-signatures-repository/atletaolympia

Caused by:
    Character '/' @ 27 is not allowed

Location:
    hyperlane-base/src/types/gcs_storage.rs:181:9', agents/validator/src/validator.rs:178:14
```

To solve this problem I added the `folder: Option<String>` field to the
GcsStorageClient structure, I also added bucket and folder processing to
the impl CheckpointSyncer, GcsStorageClientBuilder methods